version: '3.7'
services:
  nginx:
    image: nginx:1.21.5-alpine
    container_name: nginx_proxy
    ports:
      - "80:80"
    volumes:
      - ~/onroad/source/service-demo-express/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - service-demo-express
  mysql:
    image: mysql:5.7.36
    container_name: mysql
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    volumes:
      - ~/onroad/database/service-demo-express/mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: 'robots'
      MYSQL_USER: 'demo'
      MYSQL_PASSWORD: 'demo'
      MYSQL_ROOT_PASSWORD: 'demo'
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - service-demo-express

  node:
    image: node:14-alpine
    container_name: node
    working_dir: /var/www
    volumes:
      - ~/onroad/source/service-demo-express:/var/www/
    tty: true
    ports:
      - "3000"
    networks:
      - service-demo-express
    command: sh -c "npm install && npm run start"
networks:
  service-demo-express: